server:
  type: simple
  applicationContextPath: /
  connectorType: http
  port: 8080

database:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/secureline_db
  user: secureline
  password: CHANGE_ME

redis:
  url: redis://localhost:6379

security:
  zkSecret: CHANGE_ME_TO_A_LONG_RANDOM_SECRET
  unidentifiedAccessEnabled: false

logging:
  level: INFO
  loggers:
    org.whispersystems: WARN
